version: "3.8"

services:
    backend:
        container_name: backend
        build: ./example-backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
            REQUEST_ORIGIN: http://localhost
    frontend:
        container_name: frontend
        build: ./example-frontend
        environment:
            REACT_APP_BACKEND_URL: http://localhost
    redis:
        container_name: redis
        image: redis
        restart: unless-stopped
    postgres:
        container_name: postgres
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
